## Homework.4 31-A.Utilizing Numpy Function

In [1]:
import numpy as np
import numpy.linalg as NL

## 1.Create an array of size 10 filled with 0

In [2]:
a = np.zeros(10, float)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

## 2.Set fifth value to 1 from above array

In [3]:
a = np.zeros(10, float)
a[4] = 1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

## 3.Create an array with values ranging from 10 to 49

In [4]:
a = np.arange(10,50,1)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

## 4.Create a 5*5 matrix with values ranging from 0 to 24

In [5]:
a = np.arange(0,25,1).reshape((5,5))
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

## 5.Create a 5*5 identity matrix

In [6]:
a = np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## 6.Create an 5*5 array with random values and find the minimum and maximum value

In [7]:
a = np.random.random((5,5))
print('Minimum value : ', a.min(), ' Maximum value : ', a.max())

Minimum value :  0.01275130569741978  Maximum value :  0.960993792673895


## 7.Multiply a 4x3 matrix by a 3x2 matrix
### 4*3 matrix is filled with 1
### 3*2 matrix is filled with random number

In [18]:
a = np.full((4,3),1)
b = np.random.randint(10, size=(3,2))

m = np.dot(a,b)
m

array([[ 9, 17],
       [ 9, 17],
       [ 9, 17],
       [ 9, 17]])

## 8.Transpose the above matrix

In [9]:
mt = m.transpose()
mt

array([[15, 15, 15, 15],
       [17, 17, 17, 17]])

## 9.Create two matrices ranging from 0 to 24 and 25 to 49

In [10]:
a = np.arange(0,25).reshape((5,5))
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [11]:
b = np.arange(25,50).reshape((5,5))
b

array([[25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

## Add to matrix

In [12]:
m_add = a+b
m_add

array([[25, 27, 29, 31, 33],
       [35, 37, 39, 41, 43],
       [45, 47, 49, 51, 53],
       [55, 57, 59, 61, 63],
       [65, 67, 69, 71, 73]])

## Substract two matrix

In [13]:
m_sub = a-b
m_sub

array([[-25, -25, -25, -25, -25],
       [-25, -25, -25, -25, -25],
       [-25, -25, -25, -25, -25],
       [-25, -25, -25, -25, -25],
       [-25, -25, -25, -25, -25]])

## Q1.다음 코드의 실행 결과의 형태를 예측하시오

In [14]:
a1_1 = np.array([[1,2],[3,4]])
a1_2 = np.array([[1,2],[3,4],[5,6]])

NL.eig(a1_1)

(array([-0.37228132,  5.37228132]), array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))

#### → a1_1 matrix의 eigen value array와 eigen vector array가 반환된다

In [15]:
NL.eig(a1_2)

LinAlgError: Last 2 dimensions of the array must be square

#### →Square Matrix가 아니므로 eigenvalue, eigenvector 계산시 오류 발생

In [ ]:
NL.svd(a1_1, full_matrices=True)

#### → a1_1 Matrix의 Singular Value Decomposition 결과인 U,S,V Matrix를 반환한다.
####  full_matrrices=True 이므로 Full SVD 결과를 반환한다

In [ ]:
NL.svd(a1_1, full_matrices=False)

#### → a1_1 Matrix의 Singular Value Decomposition 결과인 U,S,V Matrix를 반환한다.
####  full_matrrices=False 이므로 Reduce SVD 결과를 반환한다

In [ ]:
NL.svd(a1_2, full_matrices=True)

#### → a1_2 Matrix의 Singular Value Decomposition 결과인 U,S,V Matrix를 반환한다.
####  full_matrrices=True 이므로 Full SVD 결과를 반환한다

In [ ]:
NL.svd(a1_2, full_matrices=False)

#### → a1_2 Matrix의 Singular Value Decomposition 결과인 U,S,V Matrix를 반환한다.
####  full_matrrices=False 이므로 Reduce SVD 결과를 반환한다

##  Q2. 주어진 코드와 실행 결과가 다음과 같을 때, 결과 값 x,y의 의미와 그 관계에 대해 설명하시오.

In [ ]:
a2 = np.array([[7,1],[1,7]])
x,y = NL.eig(a2)
x,y

#### → x = a2 matrix의 eigen value
#### → y = a2 matrix의 eigen vector

## Q3. 주어진 코드의 실행 결과인 U, S, V의 형태를 예측하고, 각 결과 값이 의미하는 바를 쓰시오.

In [ ]:
a3 = np.array([[1,1,1,0,0,],[3,3,3,0,0],[4,4,4,0,0],[5,5,5,0,0],[0,2,0,4,4],[0,0,0,5,5],[0,1,0,2,2]])
U,S,V = NL.svd(a3, full_matrices=False)
U,S,V

#### full_matrices = False 이므로 reduce SVD  결과를 반환한다
#### U : a3를 고유값 분해하여 얻어진 orthogonal matrix (Left singular vector)  - 5x7 matrix
#### S : a3를 고유값 분해하여 얻어진 eigen value array (singular value) - 5개
#### V : a3를 고유값 분해하여 얻어진 orthogonal matrix (Right singular vector) - 5x5 matrix