In [2]:
import numpy as np

a = np.array([[1,2,3],[4,5,6]],float)
a

array([[1., 2., 3.],
       [4., 5., 6.]])

In [2]:
b = np.arange(0.,5.,0.3)
b

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8, 2.1, 2.4, 2.7, 3. , 3.3, 3.6,
       3.9, 4.2, 4.5, 4.8])

In [3]:
c = np.zeros((2,4))
c

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [4]:
d = np.full((2,4),7)
d

array([[7, 7, 7, 7],
       [7, 7, 7, 7]])

In [5]:
e = np.ones((2,3))
e

array([[1., 1., 1.],
       [1., 1., 1.]])

In [6]:
f = np.eye(5)
f

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [7]:
## 0.0 ~ 1.0 사이의 Random 값 반환
g = np.random.random((2,3))
g

array([[0.96035745, 0.99948778, 0.15035878],
       [0.75189795, 0.99893444, 0.62940973]])

In [8]:
## 0.0 ~ 1.0 사이의 Uniform Distribution값 반환
h = np.random.rand(2,3)
h

array([[0.11375043, 0.25933227, 0.3401893 ],
       [0.04713719, 0.29341176, 0.7312013 ]])

In [9]:
## 0 ~ 10 사이의 랜덤정수 7개 반환
i = np.random.randint(10, size=7)
i

array([8, 7, 2, 5, 5, 7, 7])

In [10]:
## 0 ~ 10 사이의 랜덤정수를 2x4 matrix로 반환
j = np.random.randint(10, size=(2,4))
j

array([[5, 4, 7, 1],
       [2, 4, 2, 6]])

In [11]:
## 평균 3, 분산 6.25인 정규분포를 3x4 matrix로 반환
k = 2.5 * np.random.randn(3, 4) + 3
k

array([[-0.14813251,  5.29774008,  1.19603923,  3.5791788 ],
       [ 8.9011842 ,  4.09306358,  7.24141479, -2.01216326],
       [ 3.80023272,  4.72559361,  2.0945757 , 10.69411525]])

In [22]:
## row,col operation
l = np.array([[1,2,3],[4,5,6]], float)
#l[1,:]
#l[:,1:]
l[-1:,-2:]

array([[5., 6.]])

In [13]:
## array to matrix
m = np.array(range(6),float)
m = m.reshape(2,3)
m.transpose()

array([[0., 3.],
       [1., 4.],
       [2., 5.]])

In [14]:
## matrix to array
m.flatten()

array([0., 1., 2., 3., 4., 5.])

In [15]:
## row concatenate
m = np.array(range(0,10,1),float).reshape(2,5)
n = np.array(range(-10,0,1),float).reshape(2,5)
np.concatenate((m,n), axis=0) ## axis=0 --> row add, axis=1 --> col add

array([[  0.,   1.,   2.,   3.,   4.],
       [  5.,   6.,   7.,   8.,   9.],
       [-10.,  -9.,  -8.,  -7.,  -6.],
       [ -5.,  -4.,  -3.,  -2.,  -1.]])

In [16]:
o = np.concatenate((m,n), axis=0)
o = o.reshape((5,4))

for row in o:
    for val in row:
        print(val)

0.0
1.0
2.0
3.0
4.0
5.0
6.0
7.0
8.0
9.0
-10.0
-9.0
-8.0
-7.0
-6.0
-5.0
-4.0
-3.0
-2.0
-1.0


In [17]:
p = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]])
for mat in p:
    print(mat)
    print('-------')

[[1 2 3]
 [4 5 6]]
-------
[[ 7  8  9]
 [10 11 12]]
-------
[[13 14 15]
 [16 17 18]]
-------


In [18]:
for mat in p:
    for row in mat:
        print(row)
        print('-------')

[1 2 3]
-------
[4 5 6]
-------
[7 8 9]
-------
[10 11 12]
-------
[13 14 15]
-------
[16 17 18]
-------


In [19]:
### array 통계연산
q = np.array([2,4,3], float)
print(q.sum(),q.prod(),q.mean(),q.var(),q.std(), np.median(q))

9.0 24.0 3.0 0.6666666666666666 0.816496580927726 3.0


In [20]:
### matrix 통계연산
q = np.array([[2,4,3],[5,8,3]], float)
print(q.sum(),q.prod(),q.mean(),q.var(),q.std(), np.median(q))

## col 연산, row 연산
print(np.sum(q, axis=0), np.sum(q, axis=1))

### concatenate 할때 axis와 사용방법이 반대이니 조심하자!!!!


25.0 2880.0 4.166666666666667 3.8055555555555554 1.9507833184532708 3.5
[ 7. 12.  6.] [ 9. 16.]


In [28]:
q

array([[2., 4., 3.],
       [5., 8., 3.]])